# Generated by Django 3.1.4 on 2021-04-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VipMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=250)),
                ('road', models.CharField(max_length=150)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
